export const USER_TYPE = {
  TRAVELER: 'TRAVELER',
  GUIDE: 'GUIDE',
} as const;

export const MODAL_TYPE = {
  WHERE: 'WHERE',
  WHEN: 'WHEN',
  WITH_WHOM: 'WITH_WHOM',
} as const;

export const MAGAZINE_TYPE = {
  NOW: 'NOW',
  FARM_EXPERIENCE: 'FARM_EXPERIENCE',
  RESTAURANT: 'RESTAURANT',
  TOURIST_ATTRACTION: 'TOURIST_ATTRACTION',
  LANDSCAPE: 'LANDSCAPE',
} as const;